block_class: example.runtime.example_block.ExampleBlock
block_id: 00110203-0405-0607-0809-0a0b02dd0e0f
created: '2023-05-24 11:35:52.788245'
example_version: 0.0.0
name: ExampleBlock
saved: '2023-05-24 11:35:52.788254'
temp_model_path: /Users/mhickey/Documents/Dev/github.com/caikit/caikit-template/client/train_output/3c624ef4-e4be-4a90-bac9-5ad414c762d3/example/temp_model.txt
tokenizer_path: <EXAMPLE>
tracking_id: 384d54a4-4754-4ada-a3a1-8d38a1465aea
version: 0.0.1
